import pytest
from mightymcp.worker_reports import parse_report

SCOUT = """
<report>
  <verdict>VERIFIED</verdict>
  <confidence>high</confidence>
  <command>rg -n "class RateLimiter" src/</command>
  <findings>
    <finding location="src/api/limits.py:17">class RateLimiter, built with Redis</finding>
  </findings>
</report>
"""
SCOUT_BLOCKED = """
<report>
  <verdict>UNKNOWN-BLOCKED</verdict>
  <confidence>low</confidence>
  <findings>
    <finding location="config/settings.py:4">read from the environment</finding>
  </findings>
  <follow_up>deploy/helm/values.yaml carries the deployed value</follow_up>
</report>
"""
ENGINEER = """
<report>
  <status>done</status>
  <group>webhook-retry</group>
  <tasks>
    <task id="T3" verified="true"/>
    <task id="T4" verified="deferred">serialized verification, edits complete</task>
  </tasks>
  <files_changed>
    <file>packages/webhooks/src/dispatch.ts</file>
  </files_changed>
  <deviation>none</deviation>
</report>
"""
ENGINEER_BLOCKED = """
<report>
  <status>blocked</status>
  <group>client-retry</group>
  <tasks>
    <task id="T5" verified="false">stopped before editing; see blocker</task>
  </tasks>
  <files_changed/>
  <deviation>none</deviation>
  <blockers>
    <blocker task="T5" location="src/api/client.py:88">send() is async</blocker>
  </blockers>
</report>
"""
BUDGETRON = """
<report>
  <status>fixed</status>
  <issue>ruff E501 in limits.py</issue>
  <verify command="uv run ruff check .">passed</verify>
  <files_changed>
    <file>src/api/limits.py</file>
  </files_changed>
</report>
"""
BUDGETRON_ESCALATED = """
<report>
  <status>escalated</status>
  <issue>ruff E501 in limits.py</issue>
  <blocker location="src/api/limits.py:17">the line is generated by a template</blocker>
</report>
"""
GITTY_UP = """
<report agent="ci-watcher" pr="214">
  <verdict>pass</verdict>
  <confidence>high</confidence>
  <findings>
    <finding location="tests" bucket="pass" link="https://ci/1">all green</finding>
  </findings>
</report>
"""
GITTY_UP_FAIL = """
<report agent="ci-watcher" pr="215">
  <verdict>fail</verdict>
  <confidence>high</confidence>
  <findings>
    <finding location="tests" bucket="fail" link="https://ci/2">pytest exited 1</finding>
  </findings>
  <logs><![CDATA[
E   assert 3 == 4
  ]]></logs>
</report>
"""
GITTY_UP_ERROR = """
<report agent="ci-watcher" pr="216">
  <verdict>error</verdict>
  <confidence>low</confidence>
  <findings>
    <finding location="none" bucket="pending">no checks reported after 120s</finding>
  </findings>
  <follow_up>wire the workflow to this base branch</follow_up>
</report>
"""
WINGMAN = """
<report agent="wingman">
  <decision>Retry in the client or in the queue consumer.</decision>
  <verdict>Retry in the consumer; the client cannot see the idempotency key.</verdict>
  <confidence level="medium">Rests on the dispatch, which named no key.</confidence>
  <verify>grep for the key in the consumer</verify>
  <follow_up>revisit when the client owns the key</follow_up>
</report>
"""
GRUMPY = """
[DEFECT] The mutex guards the write but not the read-modify-write
  Where: src/cache/store.go:142-149
  Why it breaks: get() at :131 reads outside the lock.

[QUESTION] Was the original report a lost update or a torn read? This fix
  addresses the torn read.

Checked: src/cache/store.go, cache_test.go, go test ./cache/
"""
SUNNY = """
[CONFIRMED] Writers cannot interleave on the version counter
  Where: src/cache/store.go:142-149
  Evidence: go test -race ./cache/ -count=50, clean
  Depends on it: the compare-and-swap in publisher.go:88

[UNCONFIRMED] Whether readers observe a consistent version
  Where: src/cache/store.go:131
  Would need: a test exercising get() concurrently with set()

Preserve:

- mu is taken before the version read in set(), not after

Checked: src/cache/store.go, publisher.go:60-110
"""
VALID = [
    ('scout', SCOUT, 'VERIFIED'),
    ('engineer', ENGINEER, 'done'),
    ('budgetron', BUDGETRON, 'fixed'),
    ('gitty-up', GITTY_UP, 'pass'),
    (
        'wingman',
        WINGMAN,
        'Retry in the consumer; the client cannot see the idempotency key.',
    ),
    ('grumpy', GRUMPY, 'DEFECT'),
    ('sunny', SUNNY, 'CONFIRMED'),
]
NOT_A_REPORT = 'I had a look at the branch and it seems fine to me.'


@pytest.mark.parametrize(('role', 'text', 'verdict'), VALID)
def test_every_role_parses_into_a_verdict(role: str, text: str, verdict: str) -> None:
    report = parse_report(role, text)

    assert report.refusals == []
    assert report.role == role
    assert report.verdict == verdict


@pytest.mark.parametrize(('role', 'text', 'verdict'), VALID)
def test_no_role_parses_another_role_as_not_a_report(
    role: str, text: str, verdict: str
) -> None:
    assert parse_report(role, NOT_A_REPORT).refusals


def test_scout_carries_its_command_and_findings() -> None:
    report = parse_report('scout', SCOUT)

    assert report.confidence == 'high'
    assert report.summary == 'rg -n "class RateLimiter" src/'
    assert [(f.location, f.summary) for f in report.findings] == [
        ('src/api/limits.py:17', 'class RateLimiter, built with Redis')
    ]
    assert report.blocked_at == ''


def test_scout_unknown_blocked_names_where_the_answer_lives() -> None:
    report = parse_report('scout', SCOUT_BLOCKED)

    assert report.verdict == 'UNKNOWN-BLOCKED'
    assert report.blocked_at == 'deploy/helm/values.yaml carries the deployed value'


def test_scout_unknown_blocked_falls_back_to_the_finding_location() -> None:
    report = parse_report('scout', SCOUT_BLOCKED.replace('<follow_up>x</follow_up>', ''))
    without = SCOUT_BLOCKED.replace(
        '  <follow_up>deploy/helm/values.yaml carries the deployed value</follow_up>\n',
        '',
    )

    assert report.blocked_at
    assert parse_report('scout', without).blocked_at == 'config/settings.py:4'


def test_scout_unknown_blocked_naming_nothing_is_refused() -> None:
    text = """
    <report><verdict>UNKNOWN-BLOCKED</verdict><confidence>low</confidence></report>
    """

    assert parse_report('scout', text).refusals == [
        (
            'UNKNOWN-BLOCKED names neither a follow_up nor a finding; contracts.md '
            'wants where the answer lives'
        )
    ]


def test_engineer_carries_its_tasks_and_files() -> None:
    report = parse_report('engineer', ENGINEER)

    assert report.subject == 'webhook-retry'
    assert report.summary == 'none'
    assert [(task.id, task.verified) for task in report.tasks] == [
        ('T3', 'true'),
        ('T4', 'deferred'),
    ]
    assert report.files_changed == ['packages/webhooks/src/dispatch.ts']


def test_engineer_blockers_come_back_as_findings() -> None:
    report = parse_report('engineer', ENGINEER_BLOCKED)

    assert report.verdict == 'blocked'
    assert report.files_changed == []
    finding = report.findings[0]
    assert (finding.kind, finding.task, finding.location) == (
        'blocker',
        'T5',
        'src/api/client.py:88',
    )


def test_an_engineer_task_state_outside_the_vocabulary_is_refused() -> None:
    text = ENGINEER.replace('verified="true"', 'verified="mostly"')

    assert parse_report('engineer', text).refusals == [
        "task 'T3' is verified='mostly'; expected true, false, deferred"
    ]


def test_budgetron_fixed_carries_the_verify_command() -> None:
    report = parse_report('budgetron', BUDGETRON)

    assert report.subject == 'ruff E501 in limits.py'
    assert report.summary == 'uv run ruff check .'
    assert report.files_changed == ['src/api/limits.py']


def test_budgetron_fixed_without_a_verify_is_refused() -> None:
    text = BUDGETRON.replace('<verify command="uv run ruff check .">passed</verify>', '')

    assert parse_report('budgetron', text).refusals == [
        (
            'a fixed report carries no <verify command>; a fix without its check is '
            'not reportable'
        )
    ]


def test_budgetron_escalated_carries_the_blocker() -> None:
    report = parse_report('budgetron', BUDGETRON_ESCALATED)

    assert report.verdict == 'escalated'
    assert report.findings[0].location == 'src/api/limits.py:17'


def test_budgetron_escalated_without_a_blocker_is_refused() -> None:
    text = BUDGETRON_ESCALATED.replace(
        '<blocker location="src/api/limits.py:17">the line is generated by a '
        'template</blocker>',
        '',
    )

    assert parse_report('budgetron', text).refusals == [
        'an escalated report carries no <blocker>'
    ]


def test_gitty_up_pass_does_not_stop_the_loop() -> None:
    report = parse_report('gitty-up', GITTY_UP)

    assert report.subject == '214'
    assert report.stop is False
    assert report.findings[0].kind == 'pass'


@pytest.mark.parametrize(
    ('text', 'verdict'), [(GITTY_UP_FAIL, 'fail'), (GITTY_UP_ERROR, 'error')]
)
def test_gitty_up_fail_and_error_stop_the_loop(text: str, verdict: str) -> None:
    report = parse_report('gitty-up', text)

    assert report.verdict == verdict
    assert report.stop is True


def test_gitty_up_carries_the_failing_logs() -> None:
    assert parse_report('gitty-up', GITTY_UP_FAIL).summary == 'E   assert 3 == 4'


def test_wingman_carries_the_decision_and_its_confidence() -> None:
    report = parse_report('wingman', WINGMAN)

    assert report.subject == 'Retry in the client or in the queue consumer.'
    assert report.confidence == 'medium'
    assert report.follow_up == 'revisit when the client owns the key'


def test_a_wingman_confidence_outside_the_levels_is_refused() -> None:
    text = WINGMAN.replace('level="medium"', 'level="certain"')

    assert parse_report('wingman', text).refusals == [
        "confidence 'certain' is not high, medium, low"
    ]


def test_grumpy_entries_keep_their_class_and_anchor() -> None:
    report = parse_report('grumpy', GRUMPY)

    assert [(f.kind, f.location) for f in report.findings] == [
        ('DEFECT', 'src/cache/store.go:142-149'),
        ('QUESTION', ''),
    ]
    assert report.findings[1].summary.startswith('Was the original report')
    assert report.checked.startswith('src/cache/store.go')


def test_grumpy_with_no_findings_is_still_a_report() -> None:
    report = parse_report(
        'grumpy', 'No findings above the bar.\n\nChecked: package.json diff\n'
    )

    assert report.refusals == []
    assert report.verdict == 'NONE'
    assert report.checked == 'package.json diff'


def test_a_grumpy_defect_without_a_where_line_is_refused() -> None:
    text = GRUMPY.replace('  Where: src/cache/store.go:142-149\n', '')

    assert parse_report('grumpy', text).refusals == [
        (
            "[DEFECT] 'The mutex guards the write but not the read-modify-write' "
            'carries no Where: line'
        )
    ]


def test_sunny_keeps_its_preserve_block() -> None:
    report = parse_report('sunny', SUNNY)

    assert report.verdict == 'CONFIRMED'
    assert report.preserve == ['mu is taken before the version read in set(), not after']
    assert [f.kind for f in report.findings] == ['CONFIRMED', 'UNCONFIRMED']


def test_sunny_without_a_checked_line_is_not_a_report() -> None:
    text = SUNNY.replace('Checked: src/cache/store.go, publisher.go:60-110\n', '')

    assert parse_report('sunny', text).refusals == [
        'no Checked: line; this is not a sunny report'
    ]


@pytest.mark.parametrize(
    ('role', 'text', 'expected'),
    [
        ('scout', SCOUT.replace('VERIFIED', 'MAYBE'), 'scout vocabulary'),
        ('engineer', ENGINEER.replace('<status>done', '<status>shipped'), 'engineer'),
        ('budgetron', BUDGETRON.replace('fixed', 'sorted'), 'budgetron'),
        ('gitty-up', GITTY_UP.replace('<verdict>pass', '<verdict>green'), 'gitty-up'),
        ('grumpy', GRUMPY.replace('[DEFECT]', '[OPINION]'), 'grumpy vocabulary'),
        ('sunny', SUNNY.replace('[CONFIRMED]', '[LOVELY]'), 'sunny vocabulary'),
    ],
)
def test_a_verdict_outside_the_role_vocabulary_is_refused(
    role: str, text: str, expected: str
) -> None:
    refusals = parse_report(role, text).refusals

    assert refusals
    assert any(expected in refusal for refusal in refusals)


@pytest.mark.parametrize(
    ('role', 'missing'),
    [
        ('scout', '<confidence>high</confidence>'),
        ('gitty-up', '<confidence>high</confidence>'),
    ],
)
def test_a_missing_required_tag_is_refused(role: str, missing: str) -> None:
    text = {'scout': SCOUT, 'gitty-up': GITTY_UP}[role].replace(missing, '')

    assert parse_report(role, text).refusals == [
        f'the {role} report is missing confidence'
    ]


def test_an_engineer_report_without_tasks_is_refused() -> None:
    text = ENGINEER.replace('<tasks>', '<nope>').replace('</tasks>', '</nope>')

    assert parse_report('engineer', text).refusals == [
        'the engineer report is missing tasks'
    ]


def test_a_report_that_is_not_well_formed_xml_is_refused() -> None:
    text = '<report><verdict>VERIFIED<confidence>high</confidence></report>'

    assert parse_report('scout', text).refusals
    assert 'well-formed' in parse_report('scout', text).refusals[0]


def test_an_unknown_role_is_refused() -> None:
    refusals = parse_report('merge-vader', SCOUT).refusals

    assert refusals == [
        (
            "unknown role 'merge-vader'; expected budgetron, engineer, gitty-up, "
            'grumpy, scout, sunny, wingman'
        )
    ]


def test_a_refused_report_carries_no_half_parsed_verdict() -> None:
    report = parse_report('scout', SCOUT.replace('VERIFIED', 'MAYBE'))

    assert report.verdict == ''
    assert report.findings == []


def test_an_engineer_report_with_an_empty_tasks_block_is_refused() -> None:
    text = ENGINEER.replace(
        '    <task id="T3" verified="true"/>\n'
        '    <task id="T4" verified="deferred">serialized verification, edits '
        'complete</task>\n',
        '',
    )

    assert parse_report('engineer', text).refusals == [
        'the engineer report names no task; every task is accounted for'
    ]
